config/routes.rb
Rails.application.routes.draw do
  get 'reports/contact_reports'

  get 'info/contact'

  get 'info/history'

  get 'info/services'

  get 'info/procurement'

  get 'info/packaging'

  get 'info/about'

  get 'welcome/index'

  root 'welcome#index'

  resources :info_requests

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :info_requests
  def self.match_contact_from_info_request(info_request)
    ret_contact = nil

    # Try to match existing record in contact
    if ! info_request.email_address.blank?
      ret_contact = Contact.find_by(email_address: info_request.email_address)
    end
    if ret_contact.blank? && ! info_request.phone.blank?
      ret_contact = Contact.find_by(phone: info_request.phone)
    end

    # If no contact found, create a new one if we have at least an email or phone
    if ret_contact.blank? && (! info_request.email_address.blank? || ! info_request.phone.blank?)
      ret_contact = Contact.new()
    end

    # Update our Fields
    if ! ret_contact.blank?
      ret_contact.email_address  = info_request.email_address  if ! info_request.email_address.blank?
      ret_contact.phone          = info_request.phone          if ! info_request.phone.blank?
      ret_contact.company        = info_request.company        if ! info_request.company.blank?
      ret_contact.contact_method = info_request.contact_method if ! info_request.contact_method.blank?
      ret_contact.name_first     = info_request.name_first     if ! info_request.name_first.blank?
      ret_contact.name_last      = info_request.name_last      if ! info_request.name_last.blank?
      ret_contact.title          = info_request.title          if ! info_request.title.blank?

      ret_contact.save
    end

    return ret_contact
  end

#  private

#  def should_be_updated (i_attribute, c_attribute)#
#    ret = false
#    if ! i_attribute.blank? && ( )
#
#    end

#  end
end

app/models/info_request.rb
class InfoRequest < ActiveRecord::Base
  belongs_to :contact
  #validates :contact_id, presence: true
  #def save
  #end
end

app/models/ping.rb
class Ping < ActiveRecord::Base
  validates :msg_type, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  def about
  end

  def contact
    @silly = '<u>The Evironment</u><br>'
    ENV.each do |theItem|
  	   @silly += "<br>Object: #{theItem} Of Type #{theItem.class}"
     end
     @silly = @silly.html_safe
  end

  def history
  end

  def services
  end

  def procurement
  end

  def packaging
  end


end

app/controllers/info_requests_controller.rb
class InfoRequestsController < ApplicationController
  def new
  end

  def create
    @whatjusthappened = "OK"

    @info_request = InfoRequest.new(chkparas)
    @contact = Contact.match_contact_from_info_request(@info_request)
    # Did we have enough data to create a contact?
    if @contact.blank?
      @whatjusthappened = "Not Enough Data"
    end

    if @whatjusthappened == "OK"
      @info_request.contact_id = @contact.id
    end

    if @whatjusthappened == "OK" && @info_request.valid?
      if ! @info_request.save # :validate => false
        @whatjusthappened = "**Error: #{@info_request.errors.messages}"
      end
    end

    #------------------------------------------------------------------------------
=begin
    @pingstuff = "<br>Pingstuff"
    @ping = Ping.new

    @ping.msg_type="Gen"
    @ping.msg = "Hello, we are on line: #{__LINE__}"
    if @ping.valid?
      @pingstuff += "<br>Ping is valid at line #{__LINE__}"
      @ping.save
    else
      @pingstuff += "<br>Ping is NOT valid at line #{__LINE__}"
    end

    @ping = Ping.find(7)
  #  @ping.msg_type = nil

    themsg = @ping.msg
    if ! themsg.include? "Mod"
      themsg += " Modified on Line: #{__LINE__}"
    end
    @ping.mod_count += 1
    @ping.msg = themsg
    if @ping.valid?
      @pingstuff += "<br>Ping is valid at line #{__LINE__}"
      @ping.save
    else
      @pingstuff += "<br>Ping is NOT valid at line #{__LINE__}"
    end




    @thecount = "The Present table count: #{InfoRequest.all.size}"
    @thepingcount = "The Present table count: #{Ping.all.size}"
    @last5pings = Ping.order(updated_at: :desc).first(5)
=end
  end

  private
    def chkparas
      params.require(:info_requests).permit(:comment, :company, :contact_id, :contact_method, :help_required, :email_address, :name_first, :name_last, :phone, :title )
    #  @info_request_paras = params.require(:info_requests).permit(:comment, :company, :contact_id, :contact_method, :help_required, :email, :name_first, :name_last, :phone, :title )
    #  @contact_paras = params.require(:info_requests).permit(:comment, :company, :contact_id, :contact_method, :help_required, :email, :name_first, :name_last, :phone, :title )
    end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def contact_reports
    @rows = InfoRequest.all
    @rowcount = InfoRequest.all.size

    @report = InfoRequest.joins("LEFT OUTER JOIN contacts ON contacts.id = info_requests.contact_id")\
    .select("contacts.name_last as c_last, info_requests.name_last as i_last
    , info_requests.id, info_requests.contact_id
    , contacts.name_first as c_first, info_requests.name_first as i_first
    , contacts.email_address as c_email, info_requests.email_address as i_email
    , contacts.phone as c_phone, info_requests.phone as i_phone
    , contacts.title as c_title, info_requests.title as i_title
    , contacts.company as c_company, info_requests.company as i_company
    , contacts.contact_method as c_contact_method, info_requests.contact_method as i_contact_method
    , info_requests.comment as i_comment, info_requests.help_required as i_help_required
    , info_requests.updated_at as i_updated_at, contacts.updated_at as c_updated_at
    ")\
    .order('info_requests.contact_id DESC, contacts.updated_at DESC, info_requests.updated_at DESC')
#    @report = InfoRequest.includes(:contact).where("id > 2")
#    .joins(:contacts)
#    .select("contacts.name_last, info_requests.id")
#    .order('info_requests.created_at DESC')


    @sql = @report.to_sql
    #puts @sql
  end
  def self.form_contact (the_id:, the_time:, first:, last:, title: nil, company: nil, phone: nil, email: nil, contact_method: nil)
    date = Time.parse the_time
    missing = "?"
    indent = "<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"
    result = "#{the_id}) #{date.strftime("%Y-%m-%d %H:%M:%S")}"

    ## -- Line 1 First name, last name, title, company
    result += indent
    if first.blank? then result += missing else  result += "#{first}" end
    result += "&nbsp;"
    if last.blank? then result += missing else  result += "#{last}" end
    result += "&nbsp;&nbsp;&nbsp;"
    if title.blank? then result += missing else  result += "#{title}" end
    result += "&nbsp;&nbsp;&nbsp;"
    if company.blank? then result += missing else  result += "#{company}" end

    ## -- Line 2 phone email
    result += indent
    if phone.blank? then result += missing else  result += "#{phone}" end
    result += "&nbsp;&nbsp;&nbsp;"
    if email.blank? then result += missing else  result += "#{email}" end

    ## -- Line 3 contact_method
    result += indent
    result += "<b>Contact via</b>: #{contact_method}"
    return result

  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def testor
    "Silly"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/info_requests_helper.rb
module InfoRequestsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/info/about.html.erb
<div class="jumbotron"></div>
<div class="container" style="text-align: center;">
  <%= image_tag "working.jpg", size: "400" %>
</div>
<div class="container">
  <br><br><br>
  <h3>Info#about</h3>
  <p>Find me in app/views/info/about.html.erb</p>
</div>

app/views/info/contact.html.erb
<div class="jumbotron"></div>
<div class="container">
  <h2>Contact Us</h2>
  <p>
    Please feel free to contact us if you need information, help or pricing.
  </P>
  <p>
    Send us an <a href="mailto:info@<%= Globals::company_url %>?Subject=Information%20Request">e-mail</a> at info@<%= Globals::company_url %>.
  </p>

  <p>
    Give us a call at 613.862.7540
  </p>

  <p>
    Send a Fax to 877.421.5561
  </p>
</div>

app/views/info/history.html.erb
<div class="jumbotron"></div>
<div class="container" style="text-align: center;">
  <%= image_tag "working.jpg", size: "400" %>
</div>
<div class="container">
  <br><br><br>
  <h3>Info#history</h3>
  <p>Find me in app/views/info/history.html.erb</p>
</div>

app/views/info/packaging.html.erb
<div class="jumbotron"></div>
<div class="container" style="text-align: center;">
  <%= image_tag "working.jpg", size: "400" %>
</div>
<div class="container">
  <br><br><br>
  <h3>Info#packaging</h3>
  <p>Find me in app/views/info/packaging.html.erb</p>
</div>

app/views/info/procurement.html.erb
<div class="jumbotron">
  <div class="container">
  <h3>Procurement and Other Services</h3>
  <h4>Why Should you Outsource?</h4>
  <p>

  </p>
  <h6>Outsourcing Can Save you Money</h6>
  <p>
    When you outsource to a specialized agency, you're gaining the benefit of their
    wisdom and expertise.
  </p>
</div>
<p>
  When you outsource to a specialized agency, you're gaining the benefit of their
  wisdom and expertise.
</p>
</div>

app/views/info/services.html.erb
<div class="jumbotron"></div>
<div class="container" style="text-align: center;">
  <%= image_tag "working.jpg", size: "400" %>
</div>
<div class="container">
  <br><br><br>
  <h3>Info#services</h3>
  <p>Find me in app/views/info/services.html.erb</p>
</div>

app/views/info_requests/create.html.erb
<div class="jumbotron"></div>
<div class="container">
  <% if @whatjusthappened == "OK" #-------------------------------------------%>
    <h3>Thanks, we're on it!</h3>
    <div class="row">
      <div class="col-sm-6" >
        <%= image_tag "2536.jpg", size: "300" %>
      </div>
      <div class="col-sm-6">
        Thank you for your request for further information.
        <br><br>
        Your request has been passed onto one of our Client Managers
        who will be in contact with you shortly to make sure all of your
        procurement and packaging needs are met.
      </div>
    </div>
    <% elsif @whatjusthappened == "Not Enough Data"  #-----------------------------------------------------------------%>
      <h3>Ooops, we've had a problem</h3>
      <div class="row">
        <div class="col-sm-6" >
          <%= image_tag "overworked.png", size: "300" %>
        </div>
        <div class="col-sm-6">
          We were unable to process your request as you must provide either
          a phone number or a valid email address for us to use to contact you.
          <br><br>
          Please resubmit your request, or if you prefer, call us directly at
          613.862.7540 and we'll get you the information you need.
        </div>
      </div>
  <% else #-----------------------------------------------------------------%>
    <h3>Ooops, we've had a problem</h3>
    <div class="row">
      <div class="col-sm-6" >
        <%= image_tag "overworked.png", size: "300" %>
      </div>
      <div class="col-sm-6">
        We were unable to process your request
        <br><br>
        Our technical staff has been informed and we will be endeavouring to
        solve this problem. If you have persistent problems with this please call
        us at 613.862.7540 and report your problem
        <br><br>
        Error: <%= @whatjusthappened %>
      </div>
    </div>
  <% end #------------------------------------------------------------------%>




</div>

app/views/info_requests/new.html.erb
<div class="jumbotron"></div>
<div class="container">
  <h2>Request More Info</h2>
  <p>
    Thank you for your interest in <%= Globals::company_name %> and our
    products and services.  Since we provide customized solutions for our
    clients please fill out the following form outlining your needs and requirements.
    We will promptly respond to make sure that you have all the information and pricing that
    you need.
  </p>
  <hr>
  <%= form_for :info_requests, url: info_requests_path do |f| %>
  <div class="row">
    <div class="col-sm-12" ><h4>Tell us about yourself</h4></div>
  </div>

  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" >First Name</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.text_field :name_first, size: 60 %></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" >Last Name</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.text_field :name_last, size: 60 %></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" >Title</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.text_field :title, size: 30 %></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" >Company</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.text_field :company, size: 50 %></div>
  </div>

  <div class="row">
    <div class="col-sm-12" ><h4>Tell us how to contact you</h4></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" ><%= f.label :email %></div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.text_field :email, size: 100 %></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" ><%= f.label :phone %></div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.telephone_field :phone %></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right" >Please contact me via</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.select :contact_method, ["email","Phone - Anytime","Phone - 9AM to Noon, Eastern","Phone - Noon to 5PM, Eastern"] %></div>
  </div>
  <div class="row">
    <div class="col-sm-12" ><h4>Tell us how we can help you</h4></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right " >I need help with</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.select :help_required, ["-- select --","Standard Box Pricing","Custom Boxes","Packaging Design","Shipping Supplies","Other"] %></div>
  </div>
  <div class="row">
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-2 text-right " ><%= f.label :comment %></div>
    <div class="col-sm-1">&nbsp;</div>
    <div class="col-sm-7"><%= f.text_area :comment %></div>
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

  <title><%= Globals::company_name %></title>
  <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css', media: 'all' %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'http://ajax.googleapis.com/agax/libs/jquery/1.12.0/jquery.min.js' %>
  <%= javascript_include_tag 'http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js' %>
  <%= csrf_meta_tags %>
  <% phil="Phil is Good" %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/"><%= Globals::company_name %></a>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Packaging", controller:"info", action: "packaging" %></li>
        <li><%= link_to "Procurement", controller:"info", action: "procurement"  %></li>
        <li><%= link_to "Services", controller:"info", action: "services"  %></li>
        <li><%= link_to "Request More Info", controller:"info_requests", action: "new"  %></li>
        <li><%#= link_to "Request Info", controller:"req_contact", action: "contact_me"  %></li>
        <li><%= link_to "Contacts", controller:"reports", action: "contact_reports"  %></li>
        <li><%= link_to "About #{Globals::company_name_short}", controller:"info", action: "about"  %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/info/contact"><span class="glyphicon glyphicon-user"></span>Contact Us</a></li>
      </ul>
    </div>
  </nav>


<%= yield %>

<hr>
<footer class="container-fluid">
  <p>
    <br><br>
    &copy;2016 <%= Globals::company_name %><br>a business unit of International Data Enginering Inc.
    <br>

    <br>
    <blockquote>
      If you haven't got time to understand ROR properly, you haven't
      got any of my time.
      <footer>Larry "LJ" Reid</footer>
    </blockquote>
    <br>
    <%= t=Time.new; t.strftime("%A, %d %b %Y %H:%M:%S %Z") %>
  </p>
</footer>

</body>
</html>

app/views/reports/contact_reports.html.erb
<div class="jumbotron"></div>
<div class="container">

  <h1>Reports#contact_reports</h1>
  <p>Find me in app/views/reports/contact_reports.html.erb</p>
  <p>There are <%= @rowcount %> rows in the info_requests table</p>

<table>
  <tr>
    <th style="border: 1pt solid blue; padding: 5pt;">Contact</th>
    <th style="border: 1pt solid blue; padding: 5pt;">Info Request</th>
  </tr>
<%
=begin
<tr>
  <th style="border: 1pt solid blue; padding: 5pt;">id</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Name</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Title</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Email Address</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Phone</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Company</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Contact Using</th>

  <th style="border: 1pt solid blue; padding: 5pt;">id</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Name</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Title</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Email Address</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Phone</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Company</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Contact Using</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Help With</th>
  <th style="border: 1pt solid blue; padding: 5pt;">Comment</th>
</tr>
=end
%>
  <% puts "Do we at least get this far??"
  <% last_id = -1 %>
  <% @report.each do |arow| %>
    <%
    if last_id != arow.contact_id  &&  arow.contact_id != nil
      contact_cell = ReportsController.form_contact(the_id: arow.contact_id, the_time: arow.c_updated_at, first: arow.c_first, last:arow.c_last, title: arow.c_title, company:  arow.c_company, phone: arow.c_phone, contact_method: arow.c_contact_method, email: arow.c_email)
    elsif last_id != arow.contact_id  &&  arow.contact_id == nil
      contact_cell = "No Contact"
    else
      contact_cell = "&nbsp;"
    end if

    request_cell = ReportsController.form_contact(the_id: arow.id, the_time: arow.i_updated_at, first: arow.i_first, last:arow.i_last, title: arow.i_title, company:  arow.i_company, phone: arow.i_phone, contact_method: arow.i_contact_method, email: arow.i_email)
    request_cell +=  "<br>&nbsp;<b>Help Required:</b> #{arow.i_help_required}"  if arow.i_help_required != "-- select --"
    request_cell +=  "<br>&nbsp;<b>Comments:</b> #{arow.i_comment}"  if ! arow.i_comment.blank?

    last_id = arow.contact_id
     %>
 <tr>
   <td style="border: 1pt solid blue; padding: 5pt;"><%= contact_cell.html_safe %></td>
   <td style="border: 1pt solid blue; padding: 5pt;"><%= request_cell.html_safe %></td>
 </tr>

<% end %>
</table>
</div>

app/views/welcome/index.html.erb
  <div class="jumbotron">
    <div class="container">
      <h2><%= Globals::company_name %></h2>
      <p class="regular">
        You provide the product development and build expertise, we help you
        get the product safely out the door and into your customer's hands
      </p>
      <div class="row">
        <div class="col-sm-7">
          <div id="myCarousel" class="carousel slide" data-ride="carousel" style="width: 90%;">
            <!-- Inidicators -->
            <ol class="carousel-indicators">
              <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
              <li data-target="#myCarousel" data-slide-to="1"></li>
              <li data-target="#myCarousel" data-slide-to="2"></li>
              <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>

            <!-- Wrapper for Slides -->
            <div class="carousel-inner" role="listbox">
              <div class="item active">
                <%= image_tag("boxes_m.jpg", size: '185') %>
                <div class="carousel-caption">
                  <span  class="c-caption">
                    <%= Globals::company_name_short %> can supply custom boxes to meet your shipping needs
                  </span>
                </div>
              </div>
              <div class="item">
                <%= image_tag("bubble_m.jpg", width: '185') %>
                <div class="carousel-caption">
                  <span  class="c-caption">
                    <%= Globals::company_name_short %> can help you design proper packaging to protect your valuable shipment
                  </span>
                </div>
              </div>
              <div class="item">
                <%= image_tag("strong_m.jpg", width: '250') %>
                <div class="carousel-caption">
                  <span  class="c-caption">
                    <%= Globals::company_name_short %> can help you select the correct material for your shipping containers
                  </span>
                </div>
              </div>
              <div class="item">
                <%= image_tag("supplies_m.jpg", width: '185') %>
                <div class="carousel-caption">
                  <span  class="c-caption">
                    <%= Globals::company_name_short %> is your source for all of your shipping supplies
                  </span>
                </div>
              </div>
            </div>
              <!-- Left and Right Controls -->
              <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
              </a>
              <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
              </a>
          </div>
        </div>
        <div class="col-sm-5">
          <p class="regular">
            Often overlooked, you can off-load to <%= Globals::company_name %> all of the problems
            of designing and procuring the necessary packaging materials so that
            your product reaches your customer's site safely.
          </p>
          <button type="button" class="btn-primary btn-lg">Learn More</button>
        </div>
      </div>
    </div>
  </div>

  <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h2>Packaging</h2>
          <p class="regular">
            <%= Globals::company_name_short %> specializes in providing small or limited volume
            custom and standard packaging.  Provide us with the size, shape and weight of
            your product and we will work with you to create the correct package for your
            shipping needs.
          </p>
          <p><a class="btn btn-default" href="#" role="button">More details &raquo;</a></p>
        </div>
        <div class="col-md-4">
          <h2>Procurement</h2>
          <p class="regular">
            Don't have the time to spend identifying, selecting and qualifying vendors?
            Don't know where to find that key part or service?  <%= Globals::company_name_short %>
            can help.  Our team has years of experience sourcing components, packaging, shipping
            supplies and hard to source parts.
          </p>
          <p>
            <a class="btn btn-default" href=<%= url_for controller:"info", action: "procurement"  %> role="button">More details &raquo;</a>
          </p>
        </div>
        <div class="col-md-4">
          <h2>Our History</h2>
          <p class="regular">
            <%= Globals::company_name_short %> started out as <mark>Stewart Packaging</mark>.
              We were founded, in 2008, by Craig Stewart as a service to small businesses to
              provide specialized packaging and supplies. We continue to expand our
              capabilities while staying faithful to Craig's founding
              principles of high quality and responsive service.
          </p>
          <p><a class="btn btn-default" href="#" role="button">More details &raquo;</a></p>
        </div>
      </div>
      <br><hr><br>

  </div>